### ISSUE TITLE
Use NFP Accelerator without Customer Engagement

### ISSUE THREAD

**Issue by mierlo** [Microsoft/Dynamics-365-Industry-Accelerators#31]
Is it possible to use this accelrator without a valid Dymanics 365 Customer Engagement instance? I tried to import the solution but always got an error that references are missing

**Comment by mgernaey** [comment]
>           Is it possible to use this accelrator without a valid Dymanics 365 Customer Engagement instance? I tried to import the solution but always got an error that references are missing

No, you are required to have at least 1 license for the items. Since this is CE, that's how the dependencies work. You can use a trial instance and configure the require components there. In the future there will be a version that works with CDS (Power Apps) and it will only support the entities themselves and therefor would require a Power Apps Dev only usage, but you will lose all the forms etc.

**Comment by mierlo** [comment]
understood, thanks for the feedback.
