### ISSUE TITLE
Dynamics portal

### ISSUE THREAD

**Issue by mwolfaardt** [microsoft/Dynamics-365-Industry-Accelerators#34]
**Is your feature request related to a problem? Please describe.**
Enable the portal capabilities for patients to log requests with practitioners

**Describe the solution you'd like**
A deployment of the dynamics portal with bots support, where patients can interact with practitioner and booking 

**Describe alternatives you've considered**
PowerApps

**Additional context**
N/A

**Comment by mgernaey** [comment]
Thanks for the suggestion. We aren't targeting to release a portal because we aren't focusing on really being a first party app, just an accelerator. That being said, what we are hoping is that folks like yourself will contribute to the accelerator, whether it ends up being actual direct additions, or viral samples in git, or samples in GIT / AppSource. We can definitely put this as a suggestion in our delivery list, but a good chance it would have to come from another delivery mechanism.
